
Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu_aws"
   config.vm.synced_folder ".", "/vagrant",disabled:true
   config.vm.provision "shell",path:"script/initialize.sh"
   config.vm.provider :aws do |aws, override|	
    aws.access_key_id = "" ##Acces key id need to be changed
    aws.secret_access_key = ""	##Access secret key
    aws.keypair_name = "keyForAmazon"   ##Key pair name need to be changed
    override.ssh.private_key_path = "/home/ubuntu/keyForAmazon.pem"  ##key file need to be changed
    override.ssh.username = "ubuntu"
    aws.instance_type = "t2.micro"
    aws.security_groups = "default"
    aws.region='ap-south-1'
    aws.ami = "ami-4a90fa25"
    aws.tags = {
      'Name' => 'PuppetAws',
     }
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "init.pp"
    puppet.module_path= "puppet/modules"
  end
end
